model:
  hifigan_checkpoint: src/weights/convtasnet.pth
  output_dir: ./predictions

data:
  data_dir: None
  extension: .txt

text: "Dmitri Shostakovich was a Soviet-era Russian composer and pianist who became internationally known after the premiere of his First Symphony in 1926 and thereafter was regarded as a major composer."