_target_: src.logger.WandBWriter
project_name: "HIFI-GAN-HW3"
entity: null
run_name: "train#2-continue"
mode: "online"
loss_names: ["gen_loss", "loss_adv", "loss_mel", "loss_fm", "disc_loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
